services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ./build/server 4000
    ports:
      - "4000:4000/udp"
    networks:
      - pix-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  client1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - pix-network
    depends_on:
      - server
    volumes:
      - ./test:/app/test
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  client2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - pix-network
    depends_on:
      - server
    volumes:
      - ./test:/app/test
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  client3:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - pix-network
    depends_on:
      - server
    volumes:
      - ./test:/app/test
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  pix-network:
    driver: bridge
